### ISSUE TITLE
Filter by geometry type

### ISSUE THREAD

**Issue by maning** [mapbox/osm-tag-stats#14]
Following the [gl-style-spec](https://www.mapbox.com/mapbox-gl-style-spec/#types), I created a filter to get only highways as LineString

```
[
  "all",
    ["has", "highway"]
    ["==", "$type", "LineString"]

]
```

But the output has has all geometry types, see snippets:

```
{"type":"Feature","geometry":{"type":"Point","coordinates":[-118.41424137353897,33.983586901834585]},"properties":{"_osm_node_id":26427564,"_version":4,"_changeset":253859,"_uid":36489,"_user":"jerjozwik","_timestamp":1223738963,"highway":"turning_circle"}},
...
"geometry":{"type":"Polygon","coordinates":[[[-118.41581591404974,33.98163524781012],[-118.41578632593155,33.981622528550375],[-118.41576042585075,33.981588402002544],
...
```

**Comment by arunasank** [comment]
@maning Just tested this, and I think it works for me, in the sense that I didn't get any hits in the resulting files for `grep -n '"geometry":{"type":"Point"}` or `grep -n '"geometry":{"type":"Polygon"}'`. There's a comma missing in the filter - it should be:
```
[
  "all",
    ["has", "highway"],
    ["==", "$type", "LineString"]

]
```
Not sure if the filter is behaving weirdly because of that - weird that it's even getting parsed by JSON.parse(). 

It'll be super if you could fix that and retry to see if it works!

**Comment by arunasank** [comment]
I take ^ back. I don't get any features for the above filter as well.

cc/ @mourner @lucaswoj - what are we missing?

**Comment by mourner** [comment]
@arunasank this is a tricky situation. `feature-filter` filters objects decoded from vector tiles which are not exactly GeoJSON-like. They have the form `{type: <number>, properties: {...}}`, whereas types in GeoJSON are strings in `geometry.type` field. For now, as a workaround, you could filter features like this:

```js
var types = ['Unknown', 'Point', 'LineString', 'Polygon'];
...
filterFn({properties: feature.properties, type: types.indexOf(feature.geometry.type)})
```

@jfirebaugh do we want to make `feature-filter` more generic for cases like this? If so, how should it look?

**Comment by jfirebaugh** [comment]
Yeah, I think making `feature-filter` support standard GeoJSON Features is a good idea. Someone want to open an issue (or send a PR)?

**Comment by james2432** [comment]
Has this been implemented or worked on? I still can't filter features.
